// コマンドタイプ定数
export const CMD = {
  BG: "bg",
  BGM: "bgm",
  BGM_STOP: "bgm_stop",
  SE: "se",
  CHARA: "chara",
  CHARA_MOD: "chara_mod",
  CHARA_HIDE: "chara_hide",
  DIALOG: "dialog",
  CHOICE: "choice",
  EFFECT: "effect",
  WAIT: "wait",
  JUMP: "jump",
  LABEL: "label",
  CG: "cg",
  NVL_ON: "nvl_on",
  NVL_OFF: "nvl_off",
  NVL_CLEAR: "nvl_clear",
};

// アクションタイプ定数
export const ACTION = {
  SET_SCRIPT_INDEX: "SET_SCRIPT_INDEX",
  SET_DISPLAYED_TEXT: "SET_DISPLAYED_TEXT",
  SET_TYPING: "SET_TYPING",
  SET_SPEAKER: "SET_SPEAKER",
  SET_BG: "SET_BG",
  BG_TRANSITION_END: "BG_TRANSITION_END",
  SET_CHARA: "SET_CHARA",
  MOD_CHARA: "MOD_CHARA",
  REMOVE_CHARA: "REMOVE_CHARA",
  SHOW_CHOICE: "SHOW_CHOICE",
  HIDE_CHOICE: "HIDE_CHOICE",
  ADD_BACKLOG: "ADD_BACKLOG",
  TOGGLE_BACKLOG: "TOGGLE_BACKLOG",
  TOGGLE_CONFIG: "TOGGLE_CONFIG",
  SHOW_SAVELOAD: "SHOW_SAVELOAD",
  HIDE_SAVELOAD: "HIDE_SAVELOAD",
  SET_TEXT_SPEED: "SET_TEXT_SPEED",
  TOGGLE_AUTO: "TOGGLE_AUTO",
  SET_BGM: "SET_BGM",
  SET_SE: "SET_SE",
  SAVE_GAME: "SAVE_GAME",
  LOAD_GAME: "LOAD_GAME",
  CLOSE_ALL_UI: "CLOSE_ALL_UI",
  // wait / jump / label
  START_WAIT: "START_WAIT",
  END_WAIT: "END_WAIT",
  // 画面エフェクト
  START_EFFECT: "START_EFFECT",
  EFFECT_END: "EFFECT_END",
  // BGM 停止
  STOP_BGM: "STOP_BGM",
  // 音量
  SET_VOLUME_MASTER: "SET_VOLUME_MASTER",
  SET_VOLUME_BGM: "SET_VOLUME_BGM",
  SET_VOLUME_SE: "SET_VOLUME_SE",
  // スキップ
  SET_SKIP_MODE: "SET_SKIP_MODE",
  SET_CTRL_PRESSED: "SET_CTRL_PRESSED",
  // キャラアニメーション
  REMOVE_CHARA_DONE: "REMOVE_CHARA_DONE",
  CHARA_ANIM_DONE: "CHARA_ANIM_DONE",
  // CG
  SHOW_CG: "SHOW_CG",
  HIDE_CG: "HIDE_CG",
  // NVL
  SET_NVL_MODE: "SET_NVL_MODE",
  ADD_NVL_TEXT: "ADD_NVL_TEXT",
  CLEAR_NVL: "CLEAR_NVL",
  // セーブ
  SET_SAVES: "SET_SAVES",
};
